services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    command: python manage.py runserver 0.0.0.0:8000

  # ⚠️ This Docker setup is optimized for development:
  # - Code is bind-mounted for live reloads
  # - node_modules is mounted separately to avoid overwrite
  # - Commands are run at startup for convenience
  # Production note: build a separate image with COPY + pnpm build instead of using bind mounts.
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  # prevents node_modules from being clobbered by bind mount
    ports:
      - "5173:5173"
    # Install deps and start Vite dev server on container startup.
    # We avoid COPY in Dockerfile to support hot reload via bind mount.
    command: sh -lc "pnpm install --frozen-lockfile=false && pnpm dev"
    depends_on:
      - backend
    environment:
      VITE_API_BASE: http://backend:8000

volumes:
  frontend_node_modules:
